name: API Call Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  api-call-job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install required tools
      run: |
        sudo apt-get update
        sudo apt-get install -y curl jq

    - name: Make API Call and Format Response
      run: |
        echo "Calling API: https://app.myriadflow.com/brands/all"
        response=$(curl -s -X GET "https://app.myriadflow.com/brands/all")
        echo "Formatted Response:"
        echo "$response" | jq
